### ISSUE TITLE
add root and power

### ISSUE THREAD

**Issue by stigl-cc** [poggingfish/plisp#5]
Please add root and power functions to number
6^
...

**Comment by poggingfish** [comment]
Do you mean like ^(6)(exponent)?

**Comment by poggingfish** [comment]
And root will be coming shortly

**Comment by poggingfish** [comment]
Could you give me an example of what you think the root function would look like?

**Comment by stigl-cc** [comment]
\(rootor[default 2])(rooted number)

**Comment by poggingfish** [comment]
@StiglCZ Completed in newest PR
